"""
Memory Models — Unified data schema for all memory types.

Single MemoryEntry schema handles ALL memory types via metadata.
No specialized stores for conversations, projects, contacts, etc.

MemoryType is just metadata. The storage layer is unified.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Memory Types
# ---------------------------------------------------------------------------


class MemoryType(Enum):
    """All supported memory types — stored as metadata, not separate tables."""

    CONVERSATION = auto()    # Chat history, user queries, responses
    PREFERENCE = auto()      # User preferences, settings, style choices
    PROJECT = auto()         # Project structure, dependencies, code context
    CONTACT = auto()         # Contact info, communication history
    CODE = auto()            # Code snippets, patterns, solutions
    TASK = auto()            # Tasks, todos, reminders
    SYSTEM = auto()          # System state, mode history
    TEMPORARY = auto()       # Short-lived, auto-cleanup
    KNOWLEDGE = auto()       # Facts, information, learning
    REMINDER = auto()        # Time-based reminders
    SESSION = auto()         # Session state, active context
    BROWSER = auto()         # Browser tabs, history, bookmarks
    WORKSPACE = auto()       # Editor workspace state


# ---------------------------------------------------------------------------
# Importance Levels
# ---------------------------------------------------------------------------


class Importance(Enum):
    """Importance levels for memory prioritization."""

    CRITICAL = 1.0     # Pinned, user-saved, developer-saved
    HIGH = 0.8         # Task-related, preference, frequently referenced
    MEDIUM = 0.5       # General conversation, useful context
    LOW = 0.2          # Casual chat, temporary data
    TRIVIAL = 0.05     # Auto-summarized, to be archived


# ---------------------------------------------------------------------------
# Memory Source
# ---------------------------------------------------------------------------


class MemorySource(Enum):
    """Source of the memory entry."""

    USER = auto()           # Explicitly created by user
    MJ = auto()             # Auto-generated by MJ
    SYSTEM = auto()         # System-generated (state, mode)
    DEVELOPER = auto()      # Developer agent
    IMPORT = auto()         # Imported from external source
    INFERRED = auto()       # Learned from patterns


# ---------------------------------------------------------------------------
# Memory Entry — THE universal schema
# ---------------------------------------------------------------------------


@dataclass
class MemoryEntry:
    """Universal memory entry — ALL memory types use this schema.

    No separate classes for Conversation, Project, Contact, etc.
    Difference is only in 'memory_type' and 'metadata' fields.
    """

    # Core identifiers
    id: str = ""                       # Unique ID (UUID)
    memory_type: str = "CONVERSATION"  # MemoryType enum name
    source: str = "MJ"                 # MemorySource enum name

    # Content
    title: str = ""                    # Short title/headline
    content: str = ""                  # Full content
    summary: str = ""                  # Auto-generated summary
    metadata: dict[str, Any] = field(default_factory=dict)  # Type-specific data

    # Embedding & Search
    embedding: Optional[list[float]] = None  # Vector embedding
    embedding_model: str = ""                # Which model generated this

    # Importance & Lifecycle
    importance: float = 0.5             # 0.0 (trivial) to 1.0 (critical)
    importance_factors: dict[str, float] = field(default_factory=dict)  # Breakdown

    # Tags & Classification
    tags: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)

    # Timestamps
    created_at: float = 0.0            # Unix timestamp
    updated_at: float = 0.0            # Last modification
    accessed_at: float = 0.0           # Last access
    expires_at: Optional[float] = None # Auto-delete after this

    # Status flags
    pinned: bool = False               # User-pinned (never auto-delete)
    archived: bool = False             # Archived (not deleted)
    deleted: bool = False              # Soft-deleted

    # Analytics
    access_count: int = 0              # Times retrieved
    update_count: int = 0              # Times updated
    reference_count: int = 0           # Times referenced by other memories/agents

    # Relation
    parent_id: Optional[str] = None    # Parent memory (for threading)
    related_ids: list[str] = field(default_factory=list)  # Related memories

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        result = {}
        for k, v in self.__dict__.items():
            if k == 'memory_type' and isinstance(v, Enum):
                result[k] = v.name if hasattr(v, 'name') else v
            elif k == 'source' and isinstance(v, Enum):
                result[k] = v.name if hasattr(v, 'name') else v
            elif k == 'importance' and isinstance(v, Enum):
                result[k] = v.value if hasattr(v, 'value') else v
            else:
                result[k] = v
        return result

    @classmethod
    def from_dict(cls, data: dict) -> "MemoryEntry":
        """Create from dictionary (from storage)."""
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    @property
    def is_expired(self) -> bool:
        """Check if this memory has expired."""
        if self.expires_at is None:
            return False
        import time
        return time.time() > self.expires_at

    @property
    def age_hours(self) -> float:
        """Age of this memory in hours."""
        import time
        return (time.time() - self.created_at) / 3600


# ---------------------------------------------------------------------------
# Query & Result types
# ---------------------------------------------------------------------------


@dataclass
class MemoryQuery:
    """Query parameters for memory search/recall."""

    text: str = ""                       # Search text / natural language query
    memory_type: Optional[str] = None    # Filter by MemoryType
    tags: list[str] = field(default_factory=list)
    importance_min: float = 0.0
    source: Optional[str] = None
    pinned_only: bool = False
    include_archived: bool = False
    limit: int = 10
    min_score: float = 0.3               # Minimum relevance score
    use_semantic: bool = True            # Use vector search
    use_keyword: bool = True             # Use keyword search


@dataclass
class MemoryResult:
    """Result from a memory search operation."""

    entry: MemoryEntry
    score: float = 0.0                   # Combined relevance score
    vector_score: float = 0.0            # Semantic similarity score
    keyword_score: float = 0.0           # Keyword match score
    importance_score: float = 0.0        # Importance factor
    recency_score: float = 0.0           # Recency factor
    rank: int = 0                        # Final rank

    def to_dict(self) -> dict[str, Any]:
        return {
            "entry": self.entry.to_dict(),
            "score": self.score,
            "vector_score": self.vector_score,
            "keyword_score": self.keyword_score,
            "importance_score": self.importance_score,
            "recency_score": self.recency_score,
            "rank": self.rank,
        }

